language: generic

dist: trusty
sudo: required

services:
  - docker

env:
  global:
    - DOCKER_IMG="maven:3-jdk"

matrix:
    include:
    - env: JDK=8
    - env: JDK=9


before_install:
  - docker pull ${DOCKER_IMG}-${JDK}

script:
  - docker run -v ${PWD}:/mnt -it ${DOCKER_IMG}-${JDK} /bin/bash -c "cd /mnt; script/ci_build.sh"
